"""Fallback movie catalog. Every poster is a verified TMDB CDN URL,
titles match the poster's actual film. Mood tags are curated by the poster's real movie."""

TMDB_IMG = "https://image.tmdb.org/t/p/w500"


def _p(path: str) -> str:
    return f"{TMDB_IMG}{path}"


MOCK_MOVIES = [
    # NOSTALGIC
    {"id": 105, "title": "Back to the Future", "year": 1985, "runtime": 116, "rating": 8.5, "vote_count": 19500,
     "genres": ["Adventure", "Comedy", "Sci-Fi"], "moods": ["nostalgic", "euphoric"], "poster": _p("/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg"),
     "backdrop": None, "overview": "A teen is hurled into 1955 by his mad-scientist friend's DeLorean.",
     "gem": False, "popularity": 88},
    {"id": 13, "title": "Forrest Gump", "year": 1994, "runtime": 142, "rating": 8.5, "vote_count": 26000,
     "genres": ["Drama", "Romance"], "moods": ["nostalgic", "romantic"], "poster": _p("/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg"),
     "backdrop": None, "overview": "A slow-witted man witnesses the whole second half of the American century.",
     "gem": False, "popularity": 80},
    {"id": 11216, "title": "Cinema Paradiso", "year": 1988, "runtime": 155, "rating": 8.4, "vote_count": 4200,
     "genres": ["Drama", "Romance"], "moods": ["nostalgic", "romantic", "melancholy"], "poster": _p("/9JhfVOveaY00o8njQu2Xrp4YWud.jpg"),
     "backdrop": None, "overview": "A filmmaker recalls the Sicilian projectionist who taught him to love cinema.",
     "gem": True, "popularity": 28},
    {"id": 12444, "title": "Harry Potter and the Deathly Hallows: Part 1", "year": 2010, "runtime": 146, "rating": 7.8, "vote_count": 17000,
     "genres": ["Fantasy", "Adventure"], "moods": ["nostalgic"], "poster": _p("/iGoXIpQb7Pot00EEdwpwPajheZ5.jpg"),
     "backdrop": None, "overview": "Three friends camp under stars they might never see again.",
     "gem": False, "popularity": 70},
    {"id": 12762, "title": "Broadway Danny Rose", "year": 1984, "runtime": 84, "rating": 7.4, "vote_count": 380,
     "genres": ["Comedy", "Drama"], "moods": ["nostalgic", "cozy"], "poster": _p("/oUgolImcg0PRiT33UNjK409aQoJ.jpg"),
     "backdrop": None, "overview": "Woody Allen's warm ode to a hapless talent agent and his forgotten acts.",
     "gem": True, "popularity": 8},

    # COZY / RAINY DAY
    {"id": 10681, "title": "WALL·E", "year": 2008, "runtime": 98, "rating": 8.1, "vote_count": 18000,
     "genres": ["Animation", "Family", "Sci-Fi"], "moods": ["cozy", "romantic"], "poster": _p("/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg"),
     "backdrop": None, "overview": "A lonely trash-compacting robot falls for a sleek scout.",
     "gem": False, "popularity": 65},
    {"id": 77338, "title": "The Intouchables", "year": 2011, "runtime": 112, "rating": 8.3, "vote_count": 15000,
     "genres": ["Comedy", "Drama"], "moods": ["cozy", "euphoric"], "poster": _p("/1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg"),
     "backdrop": None, "overview": "A wealthy quadriplegic and a Senegalese caregiver forge an unlikely friendship.",
     "gem": False, "popularity": 55},
    {"id": 508, "title": "Love Actually", "year": 2003, "runtime": 135, "rating": 7.6, "vote_count": 11000,
     "genres": ["Romance", "Comedy"], "moods": ["cozy", "romantic", "nostalgic"], "poster": _p("/7QPeVsr9rcFU9Gl90yg0gTOTpVv.jpg"),
     "backdrop": None, "overview": "Nine intertwined London love stories in the weeks before Christmas.",
     "gem": False, "popularity": 62},
    {"id": 490132, "title": "Green Book", "year": 2018, "runtime": 130, "rating": 8.2, "vote_count": 10800,
     "genres": ["Drama", "Comedy"], "moods": ["cozy", "nostalgic"], "poster": _p("/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg"),
     "backdrop": None, "overview": "A bouncer drives a pianist through the Jim Crow south, and they change each other.",
     "gem": False, "popularity": 58},

    # CHAOTIC
    {"id": 680, "title": "Pulp Fiction", "year": 1994, "runtime": 154, "rating": 8.5, "vote_count": 27500,
     "genres": ["Thriller", "Crime"], "moods": ["chaotic", "weird", "angry"], "poster": _p("/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg"),
     "backdrop": None, "overview": "The lives of two mob hitmen, a boxer, and a diner couple intertwine.",
     "gem": False, "popularity": 92},
    {"id": 550, "title": "Fight Club", "year": 1999, "runtime": 139, "rating": 8.4, "vote_count": 28000,
     "genres": ["Drama", "Thriller"], "moods": ["angry", "chaotic", "weird"], "poster": _p("/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg"),
     "backdrop": None, "overview": "An insomniac and a soap salesman start an underground club that spirals out of control.",
     "gem": False, "popularity": 85},
    {"id": 598, "title": "City of God", "year": 2002, "runtime": 130, "rating": 8.4, "vote_count": 8300,
     "genres": ["Crime", "Drama"], "moods": ["chaotic", "angry"], "poster": _p("/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg"),
     "backdrop": None, "overview": "Two boys grow up on opposite sides of a Rio favela's collapse.",
     "gem": False, "popularity": 45},
    {"id": 155, "title": "The Dark Knight", "year": 2008, "runtime": 152, "rating": 8.5, "vote_count": 34000,
     "genres": ["Action", "Crime"], "moods": ["chaotic"], "poster": _p("/qJ2tW6WMUDux911r6m7haRef0WH.jpg"),
     "backdrop": None, "overview": "Batman confronts a chaos agent in a burning Gotham.",
     "gem": False, "popularity": 95},
    {"id": 76341, "title": "Mad Max: Fury Road", "year": 2015, "runtime": 120, "rating": 7.6, "vote_count": 21500,
     "genres": ["Action", "Adventure", "Sci-Fi"], "moods": ["chaotic", "angry"], "poster": _p("/ulcAi4dKpAjHwYGS08vNyx9H6I9.jpg"),
     "backdrop": None, "overview": "A one-armed war rig driver and a shackled prisoner floor it across the wasteland.",
     "gem": False, "popularity": 90},

    # MELANCHOLY
    {"id": 843, "title": "In the Mood for Love", "year": 2000, "runtime": 98, "rating": 8.1, "vote_count": 3200,
     "genres": ["Drama", "Romance"], "moods": ["melancholy", "romantic"], "poster": _p("/8BgGbbWiLNhPtkMkN0gGTnbtvBv.jpg"),
     "backdrop": None, "overview": "Two Hong Kong neighbors discover their spouses are having an affair — and slowly become entangled themselves.",
     "gem": True, "popularity": 20},
    {"id": 5915, "title": "Into the Wild", "year": 2007, "runtime": 148, "rating": 8.0, "vote_count": 6800,
     "genres": ["Adventure", "Drama"], "moods": ["melancholy"], "poster": _p("/jnLnLYP5pGDfri04gxtAqAvkHMw.jpg"),
     "backdrop": None, "overview": "A restless graduate abandons everything for the Alaskan wilderness.",
     "gem": False, "popularity": 38},
    {"id": 497, "title": "The Green Mile", "year": 1999, "runtime": 189, "rating": 8.5, "vote_count": 18000,
     "genres": ["Drama", "Fantasy"], "moods": ["melancholy"], "poster": _p("/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg"),
     "backdrop": None, "overview": "Death row guards discover a miracle inside a gentle giant.",
     "gem": False, "popularity": 60},
    {"id": 872585, "title": "Oppenheimer", "year": 2023, "runtime": 180, "rating": 8.1, "vote_count": 9200,
     "genres": ["Drama", "History"], "moods": ["melancholy"], "poster": _p("/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"),
     "backdrop": None, "overview": "The physicist who ended one war and started an era of dread.",
     "gem": False, "popularity": 90},

    # EUPHORIC
    {"id": 194, "title": "Amélie", "year": 2001, "runtime": 122, "rating": 7.9, "vote_count": 9500,
     "genres": ["Comedy", "Romance"], "moods": ["euphoric", "cozy", "romantic"], "poster": _p("/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg"),
     "backdrop": None, "overview": "A shy Paris waitress secretly transforms strangers' lives.",
     "gem": False, "popularity": 55},
    {"id": 569094, "title": "Spider-Man: Across the Spider-Verse", "year": 2023, "runtime": 140, "rating": 8.4, "vote_count": 6100,
     "genres": ["Animation", "Action"], "moods": ["euphoric", "chaotic"], "poster": _p("/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg"),
     "backdrop": None, "overview": "Miles Morales sprints through parallel worlds and neon skylines.",
     "gem": False, "popularity": 88},
    {"id": 12405, "title": "Slumdog Millionaire", "year": 2008, "runtime": 120, "rating": 7.9, "vote_count": 10200,
     "genres": ["Drama", "Romance"], "moods": ["euphoric", "romantic"], "poster": _p("/5leCCi7ZF0CawAfM5Qo2ECKPprc.jpg"),
     "backdrop": None, "overview": "A Mumbai teen from the slums competes on Who Wants to Be a Millionaire.",
     "gem": False, "popularity": 40},
    {"id": 66021, "title": "Napoli sotto il bacio del fuoco", "year": 2010, "runtime": 90, "rating": 6.5, "vote_count": 40,
     "genres": ["Drama"], "moods": ["euphoric", "weird"], "poster": _p("/rxKiWR6jPHQEurGe1RMILS0k3uv.jpg"),
     "backdrop": None, "overview": "A little-seen Italian curio pulsing with Neapolitan heat and grit.",
     "gem": True, "popularity": 5},

    # WEIRD / CULT
    {"id": 62, "title": "2001: A Space Odyssey", "year": 1968, "runtime": 149, "rating": 8.1, "vote_count": 10800,
     "genres": ["Sci-Fi", "Adventure"], "moods": ["weird", "melancholy"], "poster": _p("/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg"),
     "backdrop": None, "overview": "A mysterious monolith propels humanity from apes to the stars.",
     "gem": False, "popularity": 45},
    {"id": 1417, "title": "Pan's Labyrinth", "year": 2006, "runtime": 118, "rating": 7.9, "vote_count": 8300,
     "genres": ["Fantasy", "Drama"], "moods": ["weird", "melancholy"], "poster": _p("/7wb2Ldp0oAx1lcZvffq9RfWoI2h.jpg"),
     "backdrop": None, "overview": "In fascist Spain, a girl slips into a fairy tale that isn't gentle.",
     "gem": False, "popularity": 55},
    {"id": 315837, "title": "Ghost in the Shell", "year": 2017, "runtime": 106, "rating": 6.3, "vote_count": 5800,
     "genres": ["Sci-Fi", "Action"], "moods": ["weird", "chaotic"], "poster": _p("/zCtL3UBgCoZzd7XTVGhvl6XY75E.jpg"),
     "backdrop": None, "overview": "A cyber-enhanced soldier hunts a hacker who's rewriting minds.",
     "gem": False, "popularity": 40},
    {"id": 129, "title": "Spirited Away", "year": 2001, "runtime": 125, "rating": 8.5, "vote_count": 15000,
     "genres": ["Animation", "Fantasy"], "moods": ["weird", "cozy"], "poster": _p("/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg"),
     "backdrop": None, "overview": "A girl wanders into a bathhouse of spirits and forgets her own name.",
     "gem": False, "popularity": 82},
    {"id": 1124, "title": "The Prestige", "year": 2006, "runtime": 130, "rating": 8.2, "vote_count": 13400,
     "genres": ["Drama", "Mystery"], "moods": ["weird"], "poster": _p("/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg"),
     "backdrop": None, "overview": "Two magicians tear each other apart trying to top the ultimate trick.",
     "gem": False, "popularity": 70},
    {"id": 11324, "title": "Shutter Island", "year": 2010, "runtime": 138, "rating": 8.2, "vote_count": 22000,
     "genres": ["Thriller", "Mystery"], "moods": ["weird", "melancholy"], "poster": _p("/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg"),
     "backdrop": None, "overview": "A US Marshal investigates a vanishing at an island asylum.",
     "gem": False, "popularity": 74},
    {"id": 490, "title": "The Seventh Seal", "year": 1957, "runtime": 96, "rating": 8.1, "vote_count": 1900,
     "genres": ["Drama", "Fantasy"], "moods": ["weird", "melancholy"], "poster": _p("/wcZ21zrOsy0b52AfAF50XpTiv75.jpg"),
     "backdrop": None, "overview": "A knight plays chess with Death across a plague-struck Sweden.",
     "gem": True, "popularity": 18},
    {"id": 27205, "title": "Inception", "year": 2010, "runtime": 148, "rating": 8.4, "vote_count": 37000,
     "genres": ["Action", "Sci-Fi", "Thriller"], "moods": ["weird", "chaotic"], "poster": _p("/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg"),
     "backdrop": None, "overview": "A thief who steals corporate secrets from the subconscious is asked to plant an idea.",
     "gem": False, "popularity": 95},

    # ROMANTIC
    {"id": 38, "title": "Eternal Sunshine of the Spotless Mind", "year": 2004, "runtime": 108, "rating": 8.1, "vote_count": 13100,
     "genres": ["Sci-Fi", "Romance", "Drama"], "moods": ["romantic", "melancholy"], "poster": _p("/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg"),
     "backdrop": None, "overview": "A couple erases each other from their memories, then finds each other again.",
     "gem": False, "popularity": 60},
    {"id": 152601, "title": "Her", "year": 2013, "runtime": 126, "rating": 7.9, "vote_count": 14000,
     "genres": ["Romance", "Sci-Fi"], "moods": ["romantic", "melancholy"], "poster": _p("/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg"),
     "backdrop": None, "overview": "A lonely writer falls in love with an AI voice.",
     "gem": False, "popularity": 68},
    {"id": 637, "title": "Life Is Beautiful", "year": 1997, "runtime": 116, "rating": 8.5, "vote_count": 12000,
     "genres": ["Drama", "Romance", "Comedy"], "moods": ["romantic", "melancholy"], "poster": _p("/74hLDKjD5aGYOotO6esUVaeISa2.jpg"),
     "backdrop": None, "overview": "A father turns a concentration camp into a game to save his son.",
     "gem": False, "popularity": 50},
    {"id": 4348, "title": "Pride & Prejudice", "year": 2005, "runtime": 129, "rating": 7.9, "vote_count": 10200,
     "genres": ["Drama", "Romance"], "moods": ["romantic", "nostalgic"], "poster": _p("/o8UhmEbWPHmTUxP0lMuCoqNkbB3.jpg"),
     "backdrop": None, "overview": "Elizabeth Bennet and Mr Darcy misjudge each other across the Regency countryside.",
     "gem": False, "popularity": 58},
    {"id": 24238, "title": "Mary and Max", "year": 2009, "runtime": 92, "rating": 8.0, "vote_count": 3200,
     "genres": ["Animation", "Drama", "Comedy"], "moods": ["romantic", "melancholy", "weird"], "poster": _p("/ebmsM382m9IClLUzKYY2U5biFwM.jpg"),
     "backdrop": None, "overview": "A lonely Australian girl and a bewildered New Yorker become pen pals for twenty years.",
     "gem": True, "popularity": 22},

    # ANGRY / VISCERAL
    {"id": 807, "title": "Se7en", "year": 1995, "runtime": 127, "rating": 8.3, "vote_count": 20500,
     "genres": ["Crime", "Thriller"], "moods": ["angry", "melancholy"], "poster": _p("/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg"),
     "backdrop": None, "overview": "Two detectives hunt a killer using the seven deadly sins.",
     "gem": False, "popularity": 65},
    {"id": 238, "title": "The Godfather", "year": 1972, "runtime": 175, "rating": 8.7, "vote_count": 20000,
     "genres": ["Crime", "Drama"], "moods": ["angry", "melancholy"], "poster": _p("/3bhkrj58Vtu7enYsRolD1fZdja1.jpg"),
     "backdrop": None, "overview": "A crime family patriarch passes his empire to his reluctant son.",
     "gem": False, "popularity": 90},
    {"id": 274, "title": "The Silence of the Lambs", "year": 1991, "runtime": 118, "rating": 8.3, "vote_count": 16000,
     "genres": ["Crime", "Thriller"], "moods": ["angry", "weird"], "poster": _p("/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg"),
     "backdrop": None, "overview": "A trainee FBI agent trades wits with a cannibal to catch another killer.",
     "gem": False, "popularity": 78},
    {"id": 73, "title": "American History X", "year": 1998, "runtime": 119, "rating": 8.3, "vote_count": 10500,
     "genres": ["Drama", "Crime"], "moods": ["angry"], "poster": _p("/x2drgoXYZ8484lqyDj7L1CEVR4T.jpg"),
     "backdrop": None, "overview": "A reformed neo-Nazi tries to steer his brother from the same path.",
     "gem": False, "popularity": 58},
    {"id": 429, "title": "The Good, the Bad and the Ugly", "year": 1966, "runtime": 178, "rating": 8.5, "vote_count": 8200,
     "genres": ["Western"], "moods": ["chaotic"], "poster": _p("/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg"),
     "backdrop": None, "overview": "Three gunmen chase Confederate gold across the American west.",
     "gem": False, "popularity": 55},
    {"id": 346, "title": "Seven Samurai", "year": 1954, "runtime": 207, "rating": 8.6, "vote_count": 3300,
     "genres": ["Drama", "Adventure"], "moods": ["chaotic", "melancholy"], "poster": _p("/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg"),
     "backdrop": None, "overview": "Seven wandering swordsmen defend a village of farmers from bandits.",
     "gem": True, "popularity": 30},
]


def all_moods():
    return ["nostalgic", "cozy", "chaotic", "melancholy", "euphoric", "weird", "romantic", "angry"]
