"""Fallback movie catalog. Every poster is a verified TMDB CDN URL,
titles match the poster's actual film. Mood tags are curated by the poster's real movie."""

TMDB_IMG = "https://image.tmdb.org/t/p/w500"


def _p(path: str) -> str:
    return f"{TMDB_IMG}{path}"


MOCK_MOVIES = [
    # NOSTALGIC
    {"id": 105, "title": "Back to the Future", "year": 1985, "runtime": 116, "rating": 8.5, "vote_count": 19500,
     "genres": ["Adventure", "Comedy", "Sci-Fi"], "moods": ["nostalgic", "euphoric"], "poster": _p("/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg"),
     "backdrop": None, "overview": "A teen is hurled into 1955 by his mad-scientist friend's DeLorean.",
     "gem": False, "popularity": 88},
    {"id": 13, "title": "Forrest Gump", "year": 1994, "runtime": 142, "rating": 8.5, "vote_count": 26000,
     "genres": ["Drama", "Romance"], "moods": ["nostalgic", "romantic"], "poster": _p("/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg"),
     "backdrop": None, "overview": "A slow-witted man witnesses the whole second half of the American century.",
     "gem": False, "popularity": 80},
    {"id": 11216, "title": "Cinema Paradiso", "year": 1988, "runtime": 155, "rating": 8.4, "vote_count": 4200,
     "genres": ["Drama", "Romance"], "moods": ["nostalgic", "romantic", "melancholy"], "poster": _p("/9JhfVOveaY00o8njQu2Xrp4YWud.jpg"),
     "backdrop": None, "overview": "A filmmaker recalls the Sicilian projectionist who taught him to love cinema.",
     "gem": True, "popularity": 28},
    {"id": 12444, "title": "Harry Potter and the Deathly Hallows: Part 1", "year": 2010, "runtime": 146, "rating": 7.8, "vote_count": 17000,
     "genres": ["Fantasy", "Adventure"], "moods": ["nostalgic"], "poster": _p("/iGoXIpQb7Pot00EEdwpwPajheZ5.jpg"),
     "backdrop": None, "overview": "Three friends camp under stars they might never see again.",
     "gem": False, "popularity": 70},
    {"id": 12762, "title": "Broadway Danny Rose", "year": 1984, "runtime": 84, "rating": 7.4, "vote_count": 380,
     "genres": ["Comedy", "Drama"], "moods": ["nostalgic", "cozy"], "poster": _p("/oUgolImcg0PRiT33UNjK409aQoJ.jpg"),
     "backdrop": None, "overview": "Woody Allen's warm ode to a hapless talent agent and his forgotten acts.",
     "gem": True, "popularity": 8},

    # COZY / RAINY DAY
    {"id": 10681, "title": "WALL·E", "year": 2008, "runtime": 98, "rating": 8.1, "vote_count": 18000,
     "genres": ["Animation", "Family", "Sci-Fi"], "moods": ["cozy", "romantic"], "poster": _p("/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg"),
     "backdrop": None, "overview": "A lonely trash-compacting robot falls for a sleek scout.",
     "gem": False, "popularity": 65},
    {"id": 77338, "title": "The Intouchables", "year": 2011, "runtime": 112, "rating": 8.3, "vote_count": 15000,
     "genres": ["Comedy", "Drama"], "moods": ["cozy", "euphoric"], "poster": _p("/1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg"),
     "backdrop": None, "overview": "A wealthy quadriplegic and a Senegalese caregiver forge an unlikely friendship.",
     "gem": False, "popularity": 55},
    {"id": 508, "title": "Love Actually", "year": 2003, "runtime": 135, "rating": 7.6, "vote_count": 11000,
     "genres": ["Romance", "Comedy"], "moods": ["cozy", "romantic", "nostalgic"], "poster": _p("/7QPeVsr9rcFU9Gl90yg0gTOTpVv.jpg"),
     "backdrop": None, "overview": "Nine intertwined London love stories in the weeks before Christmas.",
     "gem": False, "popularity": 62},
    {"id": 490132, "title": "Green Book", "year": 2018, "runtime": 130, "rating": 8.2, "vote_count": 10800,
     "genres": ["Drama", "Comedy"], "moods": ["cozy", "nostalgic"], "poster": _p("/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg"),
     "backdrop": None, "overview": "A bouncer drives a pianist through the Jim Crow south, and they change each other.",
     "gem": False, "popularity": 58},

    # CHAOTIC
    {"id": 680, "title": "Pulp Fiction", "year": 1994, "runtime": 154, "rating": 8.5, "vote_count": 27500,
     "genres": ["Thriller", "Crime"], "moods": ["chaotic", "weird", "angry"], "poster": _p("/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg"),
     "backdrop": None, "overview": "The lives of two mob hitmen, a boxer, and a diner couple intertwine.",
     "gem": False, "popularity": 92},
    {"id": 550, "title": "Fight Club", "year": 1999, "runtime": 139, "rating": 8.4, "vote_count": 28000,
     "genres": ["Drama", "Thriller"], "moods": ["angry", "chaotic", "weird"], "poster": _p("/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg"),
     "backdrop": None, "overview": "An insomniac and a soap salesman start an underground club that spirals out of control.",
     "gem": False, "popularity": 85},
    {"id": 598, "title": "City of God", "year": 2002, "runtime": 130, "rating": 8.4, "vote_count": 8300,
     "genres": ["Crime", "Drama"], "moods": ["chaotic", "angry"], "poster": _p("/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg"),
     "backdrop": None, "overview": "Two boys grow up on opposite sides of a Rio favela's collapse.",
     "gem": False, "popularity": 45},
    {"id": 155, "title": "The Dark Knight", "year": 2008, "runtime": 152, "rating": 8.5, "vote_count": 34000,
     "genres": ["Action", "Crime"], "moods": ["chaotic"], "poster": _p("/qJ2tW6WMUDux911r6m7haRef0WH.jpg"),
     "backdrop": None, "overview": "Batman confronts a chaos agent in a burning Gotham.",
     "gem": False, "popularity": 95},
    {"id": 76341, "title": "Mad Max: Fury Road", "year": 2015, "runtime": 120, "rating": 7.6, "vote_count": 21500,
     "genres": ["Action", "Adventure", "Sci-Fi"], "moods": ["chaotic", "angry"], "poster": _p("/ulcAi4dKpAjHwYGS08vNyx9H6I9.jpg"),
     "backdrop": None, "overview": "A one-armed war rig driver and a shackled prisoner floor it across the wasteland.",
     "gem": False, "popularity": 90},

    # MELANCHOLY
    {"id": 843, "title": "In the Mood for Love", "year": 2000, "runtime": 98, "rating": 8.1, "vote_count": 3200,
     "genres": ["Drama", "Romance"], "moods": ["melancholy", "romantic"], "poster": _p("/8BgGbbWiLNhPtkMkN0gGTnbtvBv.jpg"),
     "backdrop": None, "overview": "Two Hong Kong neighbors discover their spouses are having an affair — and slowly become entangled themselves.",
     "gem": True, "popularity": 20},
    {"id": 5915, "title": "Into the Wild", "year": 2007, "runtime": 148, "rating": 8.0, "vote_count": 6800,
     "genres": ["Adventure", "Drama"], "moods": ["melancholy"], "poster": _p("/jnLnLYP5pGDfri04gxtAqAvkHMw.jpg"),
     "backdrop": None, "overview": "A restless graduate abandons everything for the Alaskan wilderness.",
     "gem": False, "popularity": 38},
    {"id": 497, "title": "The Green Mile", "year": 1999, "runtime": 189, "rating": 8.5, "vote_count": 18000,
     "genres": ["Drama", "Fantasy"], "moods": ["melancholy"], "poster": _p("/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg"),
     "backdrop": None, "overview": "Death row guards discover a miracle inside a gentle giant.",
     "gem": False, "popularity": 60},
    {"id": 872585, "title": "Oppenheimer", "year": 2023, "runtime": 180, "rating": 8.1, "vote_count": 9200,
     "genres": ["Drama", "History"], "moods": ["melancholy"], "poster": _p("/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"),
     "backdrop": None, "overview": "The physicist who ended one war and started an era of dread.",
     "gem": False, "popularity": 90},

    # EUPHORIC
    {"id": 194, "title": "Amélie", "year": 2001, "runtime": 122, "rating": 7.9, "vote_count": 9500,
     "genres": ["Comedy", "Romance"], "moods": ["euphoric", "cozy", "romantic"], "poster": _p("/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg"),
     "backdrop": None, "overview": "A shy Paris waitress secretly transforms strangers' lives.",
     "gem": False, "popularity": 55},
    {"id": 569094, "title": "Spider-Man: Across the Spider-Verse", "year": 2023, "runtime": 140, "rating": 8.4, "vote_count": 6100,
     "genres": ["Animation", "Action"], "moods": ["euphoric", "chaotic"], "poster": _p("/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg"),
     "backdrop": None, "overview": "Miles Morales sprints through parallel worlds and neon skylines.",
     "gem": False, "popularity": 88},
    {"id": 12405, "title": "Slumdog Millionaire", "year": 2008, "runtime": 120, "rating": 7.9, "vote_count": 10200,
     "genres": ["Drama", "Romance"], "moods": ["euphoric", "romantic"], "poster": _p("/5leCCi7ZF0CawAfM5Qo2ECKPprc.jpg"),
     "backdrop": None, "overview": "A Mumbai teen from the slums competes on Who Wants to Be a Millionaire.",
     "gem": False, "popularity": 40},
    {"id": 66021, "title": "Napoli sotto il bacio del fuoco", "year": 2010, "runtime": 90, "rating": 6.5, "vote_count": 40,
     "genres": ["Drama"], "moods": ["euphoric", "weird"], "poster": _p("/rxKiWR6jPHQEurGe1RMILS0k3uv.jpg"),
     "backdrop": None, "overview": "A little-seen Italian curio pulsing with Neapolitan heat and grit.",
     "gem": True, "popularity": 5},

    # WEIRD / CULT
    {"id": 62, "title": "2001: A Space Odyssey", "year": 1968, "runtime": 149, "rating": 8.1, "vote_count": 10800,
     "genres": ["Sci-Fi", "Adventure"], "moods": ["weird", "melancholy"], "poster": _p("/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg"),
     "backdrop": None, "overview": "A mysterious monolith propels humanity from apes to the stars.",
     "gem": False, "popularity": 45},
    {"id": 1417, "title": "Pan's Labyrinth", "year": 2006, "runtime": 118, "rating": 7.9, "vote_count": 8300,
     "genres": ["Fantasy", "Drama"], "moods": ["weird", "melancholy"], "poster": _p("/7wb2Ldp0oAx1lcZvffq9RfWoI2h.jpg"),
     "backdrop": None, "overview": "In fascist Spain, a girl slips into a fairy tale that isn't gentle.",
     "gem": False, "popularity": 55},
    {"id": 315837, "title": "Ghost in the Shell", "year": 2017, "runtime": 106, "rating": 6.3, "vote_count": 5800,
     "genres": ["Sci-Fi", "Action"], "moods": ["weird", "chaotic"], "poster": _p("/zCtL3UBgCoZzd7XTVGhvl6XY75E.jpg"),
     "backdrop": None, "overview": "A cyber-enhanced soldier hunts a hacker who's rewriting minds.",
     "gem": False, "popularity": 40},
    {"id": 129, "title": "Spirited Away", "year": 2001, "runtime": 125, "rating": 8.5, "vote_count": 15000,
     "genres": ["Animation", "Fantasy"], "moods": ["weird", "cozy"], "poster": _p("/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg"),
     "backdrop": None, "overview": "A girl wanders into a bathhouse of spirits and forgets her own name.",
     "gem": False, "popularity": 82},
    {"id": 1124, "title": "The Prestige", "year": 2006, "runtime": 130, "rating": 8.2, "vote_count": 13400,
     "genres": ["Drama", "Mystery"], "moods": ["weird"], "poster": _p("/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg"),
     "backdrop": None, "overview": "Two magicians tear each other apart trying to top the ultimate trick.",
     "gem": False, "popularity": 70},
    {"id": 11324, "title": "Shutter Island", "year": 2010, "runtime": 138, "rating": 8.2, "vote_count": 22000,
     "genres": ["Thriller", "Mystery"], "moods": ["weird", "melancholy"], "poster": _p("/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg"),
     "backdrop": None, "overview": "A US Marshal investigates a vanishing at an island asylum.",
     "gem": False, "popularity": 74},
    {"id": 490, "title": "The Seventh Seal", "year": 1957, "runtime": 96, "rating": 8.1, "vote_count": 1900,
     "genres": ["Drama", "Fantasy"], "moods": ["weird", "melancholy"], "poster": _p("/wcZ21zrOsy0b52AfAF50XpTiv75.jpg"),
     "backdrop": None, "overview": "A knight plays chess with Death across a plague-struck Sweden.",
     "gem": True, "popularity": 18},
    {"id": 27205, "title": "Inception", "year": 2010, "runtime": 148, "rating": 8.4, "vote_count": 37000,
     "genres": ["Action", "Sci-Fi", "Thriller"], "moods": ["weird", "chaotic"], "poster": _p("/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg"),
     "backdrop": None, "overview": "A thief who steals corporate secrets from the subconscious is asked to plant an idea.",
     "gem": False, "popularity": 95},

    # ROMANTIC
    {"id": 38, "title": "Eternal Sunshine of the Spotless Mind", "year": 2004, "runtime": 108, "rating": 8.1, "vote_count": 13100,
     "genres": ["Sci-Fi", "Romance", "Drama"], "moods": ["romantic", "melancholy"], "poster": _p("/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg"),
     "backdrop": None, "overview": "A couple erases each other from their memories, then finds each other again.",
     "gem": False, "popularity": 60},
    {"id": 152601, "title": "Her", "year": 2013, "runtime": 126, "rating": 7.9, "vote_count": 14000,
     "genres": ["Romance", "Sci-Fi"], "moods": ["romantic", "melancholy"], "poster": _p("/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg"),
     "backdrop": None, "overview": "A lonely writer falls in love with an AI voice.",
     "gem": False, "popularity": 68},
    {"id": 637, "title": "Life Is Beautiful", "year": 1997, "runtime": 116, "rating": 8.5, "vote_count": 12000,
     "genres": ["Drama", "Romance", "Comedy"], "moods": ["romantic", "melancholy"], "poster": _p("/74hLDKjD5aGYOotO6esUVaeISa2.jpg"),
     "backdrop": None, "overview": "A father turns a concentration camp into a game to save his son.",
     "gem": False, "popularity": 50},
    {"id": 4348, "title": "Pride & Prejudice", "year": 2005, "runtime": 129, "rating": 7.9, "vote_count": 10200,
     "genres": ["Drama", "Romance"], "moods": ["romantic", "nostalgic"], "poster": _p("/o8UhmEbWPHmTUxP0lMuCoqNkbB3.jpg"),
     "backdrop": None, "overview": "Elizabeth Bennet and Mr Darcy misjudge each other across the Regency countryside.",
     "gem": False, "popularity": 58},
    {"id": 24238, "title": "Mary and Max", "year": 2009, "runtime": 92, "rating": 8.0, "vote_count": 3200,
     "genres": ["Animation", "Drama", "Comedy"], "moods": ["romantic", "melancholy", "weird"], "poster": _p("/ebmsM382m9IClLUzKYY2U5biFwM.jpg"),
     "backdrop": None, "overview": "A lonely Australian girl and a bewildered New Yorker become pen pals for twenty years.",
     "gem": True, "popularity": 22},

    # ANGRY / VISCERAL
    {"id": 807, "title": "Se7en", "year": 1995, "runtime": 127, "rating": 8.3, "vote_count": 20500,
     "genres": ["Crime", "Thriller"], "moods": ["angry", "melancholy"], "poster": _p("/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg"),
     "backdrop": None, "overview": "Two detectives hunt a killer using the seven deadly sins.",
     "gem": False, "popularity": 65},
    {"id": 238, "title": "The Godfather", "year": 1972, "runtime": 175, "rating": 8.7, "vote_count": 20000,
     "genres": ["Crime", "Drama"], "moods": ["angry", "melancholy"], "poster": _p("/3bhkrj58Vtu7enYsRolD1fZdja1.jpg"),
     "backdrop": None, "overview": "A crime family patriarch passes his empire to his reluctant son.",
     "gem": False, "popularity": 90},
    {"id": 274, "title": "The Silence of the Lambs", "year": 1991, "runtime": 118, "rating": 8.3, "vote_count": 16000,
     "genres": ["Crime", "Thriller"], "moods": ["angry", "weird"], "poster": _p("/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg"),
     "backdrop": None, "overview": "A trainee FBI agent trades wits with a cannibal to catch another killer.",
     "gem": False, "popularity": 78},
    {"id": 73, "title": "American History X", "year": 1998, "runtime": 119, "rating": 8.3, "vote_count": 10500,
     "genres": ["Drama", "Crime"], "moods": ["angry"], "poster": _p("/x2drgoXYZ8484lqyDj7L1CEVR4T.jpg"),
     "backdrop": None, "overview": "A reformed neo-Nazi tries to steer his brother from the same path.",
     "gem": False, "popularity": 58},
    {"id": 429, "title": "The Good, the Bad and the Ugly", "year": 1966, "runtime": 178, "rating": 8.5, "vote_count": 8200,
     "genres": ["Western"], "moods": ["chaotic"], "poster": _p("/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg"),
     "backdrop": None, "overview": "Three gunmen chase Confederate gold across the American west.",
     "gem": False, "popularity": 55},
    {"id": 346, "title": "Seven Samurai", "year": 1954, "runtime": 207, "rating": 8.6, "vote_count": 3300,
     "genres": ["Drama", "Adventure"], "moods": ["chaotic", "melancholy"], "poster": _p("/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg"),
     "backdrop": None, "overview": "Seven wandering swordsmen defend a village of farmers from bandits.",
     "gem": True, "popularity": 30},

    # VAMPIRE / HORROR / MONSTERS
    {"id": 628, "title": "Interview with the Vampire", "year": 1994, "runtime": 123, "rating": 7.5, "vote_count": 4600,
     "genres": ["Horror", "Drama"], "moods": ["weird", "melancholy", "romantic"],
     "keywords": ["vampire", "vampires", "gothic", "immortal", "blood", "new orleans"],
     "poster": _p("/t7NU8IcmcNBrlunCxiycX9JV7Rp.jpg"),
     "backdrop": None, "overview": "A vampire tells his 200-year story of loneliness, blood, and beauty.",
     "gem": False, "popularity": 45},
    {"id": 694, "title": "The Shining", "year": 1980, "runtime": 146, "rating": 8.2, "vote_count": 17000,
     "genres": ["Horror"], "moods": ["weird", "angry", "chaotic"],
     "keywords": ["horror", "haunted", "hotel", "ghost", "kubrick", "psychological"],
     "poster": _p("/uAR0AWqhQL1hQa69UDEbb2rE5Wx.jpg"),
     "backdrop": None, "overview": "A caretaker family unravels inside a haunted mountain hotel.",
     "gem": False, "popularity": 78},
    {"id": 1091, "title": "The Thing", "year": 1982, "runtime": 109, "rating": 8.2, "vote_count": 8600,
     "genres": ["Horror", "Sci-Fi"], "moods": ["weird", "angry", "chaotic"],
     "keywords": ["horror", "alien", "monster", "antarctic", "paranoia", "practical effects"],
     "poster": _p("/tzGY49kseSE9QAKk47uuDGwnSCu.jpg"),
     "backdrop": None, "overview": "An Antarctic crew is picked off by a shapeshifting alien.",
     "gem": False, "popularity": 50},
    {"id": 756999, "title": "The Black Phone", "year": 2021, "runtime": 103, "rating": 7.5, "vote_count": 5300,
     "genres": ["Horror", "Thriller"], "moods": ["weird", "angry"],
     "keywords": ["horror", "kidnap", "ghost", "80s", "child in danger"],
     "poster": _p("/p9ZUzCyy9wRTDuuQexkQ78R2BgF.jpg"),
     "backdrop": None, "overview": "A boy trapped in a killer's basement finds a phone that dials the dead.",
     "gem": False, "popularity": 62},
    {"id": 301365, "title": "The Neon Demon", "year": 2016, "runtime": 118, "rating": 6.2, "vote_count": 3600,
     "genres": ["Horror", "Thriller"], "moods": ["weird", "chaotic"],
     "keywords": ["fashion", "horror", "beauty", "cult", "refn", "surreal"],
     "poster": _p("/d93h9dHIez9zRg4ooG6o1ZiQ776.jpg"),
     "backdrop": None, "overview": "An aspiring model is devoured — literally — by the Los Angeles fashion scene.",
     "gem": True, "popularity": 26},

    # SPACE / SCI-FI
    {"id": 11, "title": "Star Wars", "year": 1977, "runtime": 121, "rating": 8.2, "vote_count": 20000,
     "genres": ["Adventure", "Action", "Sci-Fi"], "moods": ["nostalgic", "euphoric", "chaotic"],
     "keywords": ["space", "sci-fi", "lightsaber", "jedi", "rebellion", "george lucas"],
     "poster": _p("/fai0rspsNeJCS69wHNjOdWxcI7P.jpg"),
     "backdrop": None, "overview": "A farm boy joins a rebellion to topple a galactic empire.",
     "gem": False, "popularity": 92},
    {"id": 438631, "title": "Dune", "year": 2021, "runtime": 155, "rating": 7.8, "vote_count": 12000,
     "genres": ["Sci-Fi", "Adventure"], "moods": ["melancholy", "chaotic"],
     "keywords": ["space", "sci-fi", "desert", "sandworm", "villeneuve", "epic"],
     "poster": _p("/v1tRXZ4JtD2Iv6fjkPvT4GiwslV.jpg"),
     "backdrop": None, "overview": "A young heir walks the dunes of Arrakis toward a war of prophecy.",
     "gem": False, "popularity": 92},
    {"id": 78, "title": "Blade Runner", "year": 1982, "runtime": 117, "rating": 7.9, "vote_count": 12800,
     "genres": ["Sci-Fi", "Thriller"], "moods": ["melancholy", "weird"],
     "keywords": ["cyberpunk", "sci-fi", "replicants", "noir", "future", "rain"],
     "poster": _p("/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg"),
     "backdrop": None, "overview": "A blade runner hunts synthetic humans through a rainy neon LA.",
     "gem": False, "popularity": 72},
    {"id": 335984, "title": "Blade Runner 2049", "year": 2017, "runtime": 164, "rating": 7.6, "vote_count": 14300,
     "genres": ["Sci-Fi", "Drama"], "moods": ["melancholy", "weird"],
     "keywords": ["cyberpunk", "sci-fi", "future", "replicants", "villeneuve", "noir"],
     "poster": _p("/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg"),
     "backdrop": None, "overview": "A new blade runner uncovers a secret that could shatter what's left of society.",
     "gem": False, "popularity": 80},
    {"id": 218, "title": "The Terminator", "year": 1984, "runtime": 108, "rating": 7.7, "vote_count": 8500,
     "genres": ["Action", "Sci-Fi"], "moods": ["chaotic", "angry"],
     "keywords": ["cyborg", "time travel", "sci-fi", "80s", "cameron"],
     "poster": _p("/qvktm0BHcnmDpul4Hz01GIazWPr.jpg"),
     "backdrop": None, "overview": "A cyborg assassin is sent back in time to kill a mother before her son is born.",
     "gem": False, "popularity": 72},

    # ACTION / SUPERHERO / HEIST
    {"id": 272, "title": "Batman Begins", "year": 2005, "runtime": 140, "rating": 7.7, "vote_count": 15000,
     "genres": ["Action", "Crime", "Drama"], "moods": ["chaotic", "angry"],
     "keywords": ["batman", "superhero", "gotham", "nolan", "origin"],
     "poster": _p("/sPX89Td70IDDjVr85jdSBb4rWGr.jpg"),
     "backdrop": None, "overview": "Bruce Wayne trains in the mountains and returns to save a broken city.",
     "gem": False, "popularity": 82},
    {"id": 49026, "title": "The Dark Knight Rises", "year": 2012, "runtime": 165, "rating": 7.8, "vote_count": 21000,
     "genres": ["Action", "Crime"], "moods": ["chaotic", "angry"],
     "keywords": ["batman", "superhero", "gotham", "bane", "nolan"],
     "poster": _p("/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg"),
     "backdrop": None, "overview": "Batman crawls out of retirement to face a masked mercenary breaking Gotham.",
     "gem": False, "popularity": 88},
    {"id": 293660, "title": "Deadpool", "year": 2016, "runtime": 108, "rating": 7.6, "vote_count": 30000,
     "genres": ["Action", "Comedy"], "moods": ["chaotic", "euphoric", "weird"],
     "keywords": ["superhero", "marvel", "irreverent", "meta"],
     "poster": _p("/3E53WEZJqP6aM84D8CckXx4pIHw.jpg"),
     "backdrop": None, "overview": "A wisecracking mercenary chases the man who scarred his life.",
     "gem": False, "popularity": 90},
    {"id": 263115, "title": "Logan", "year": 2017, "runtime": 137, "rating": 7.8, "vote_count": 16500,
     "genres": ["Action", "Drama", "Sci-Fi"], "moods": ["angry", "melancholy"],
     "keywords": ["wolverine", "superhero", "marvel", "road trip", "late-career"],
     "poster": _p("/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg"),
     "backdrop": None, "overview": "An aging Wolverine drives a mutant girl through a stripped-down American west.",
     "gem": False, "popularity": 76},
    {"id": 562, "title": "Die Hard", "year": 1988, "runtime": 132, "rating": 7.8, "vote_count": 11700,
     "genres": ["Action", "Thriller"], "moods": ["chaotic", "euphoric"],
     "keywords": ["christmas", "hostage", "action", "80s"],
     "poster": _p("/7Bjd8kfmDSOzpmhySpEhkUyK2oH.jpg"),
     "backdrop": None, "overview": "A New York cop wages a one-man war in an LA skyscraper on Christmas Eve.",
     "gem": False, "popularity": 84},
    {"id": 85, "title": "Raiders of the Lost Ark", "year": 1981, "runtime": 115, "rating": 7.9, "vote_count": 9400,
     "genres": ["Adventure", "Action"], "moods": ["nostalgic", "euphoric"],
     "keywords": ["adventure", "archaeology", "80s", "spielberg"],
     "poster": _p("/ceG9VzoRAVGwivFU403Wc3AHRys.jpg"),
     "backdrop": None, "overview": "An adventurer archaeologist races the Nazis for a biblical artifact.",
     "gem": False, "popularity": 78},

    # CRIME / NEO-NOIR
    {"id": 500, "title": "Reservoir Dogs", "year": 1992, "runtime": 99, "rating": 8.1, "vote_count": 9600,
     "genres": ["Crime", "Thriller"], "moods": ["chaotic", "angry"],
     "keywords": ["heist", "tarantino", "crime", "gangsters"],
     "poster": _p("/xi8Iu6qyTfyZVDVy60raIOYJJmk.jpg"),
     "backdrop": None, "overview": "A diamond heist collapses and the crew turn on each other in a warehouse.",
     "gem": False, "popularity": 60},
    {"id": 275, "title": "Fargo", "year": 1996, "runtime": 98, "rating": 8.0, "vote_count": 7800,
     "genres": ["Crime", "Drama"], "moods": ["weird", "chaotic"],
     "keywords": ["snow", "kidnap", "coen", "quirky", "midwest"],
     "poster": _p("/rt7cpEr1uP6RTZykBFhBTcRaKvG.jpg"),
     "backdrop": None, "overview": "A pregnant sheriff unspools a snowbound crime that keeps getting stupider.",
     "gem": False, "popularity": 55},

    # COMFORT / KIDS-FRIENDLY
    {"id": 12, "title": "Finding Nemo", "year": 2003, "runtime": 100, "rating": 7.8, "vote_count": 18000,
     "genres": ["Animation", "Family"], "moods": ["cozy", "euphoric"],
     "keywords": ["pixar", "fish", "family", "ocean"],
     "poster": _p("/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg"),
     "backdrop": None, "overview": "A clownfish crosses the reef to rescue his lost son.",
     "gem": False, "popularity": 82},
    {"id": 863, "title": "Toy Story 2", "year": 1999, "runtime": 92, "rating": 7.6, "vote_count": 11500,
     "genres": ["Animation", "Family"], "moods": ["cozy", "nostalgic"],
     "keywords": ["pixar", "toys", "childhood"],
     "poster": _p("/4rbcp3ng8n1MKHjpeqW0L7Fnpzz.jpg"),
     "backdrop": None, "overview": "Woody is toy-napped and Buzz leads a rescue across a suburban sprawl.",
     "gem": False, "popularity": 70},
    {"id": 177572, "title": "Big Hero 6", "year": 2014, "runtime": 102, "rating": 7.7, "vote_count": 13000,
     "genres": ["Animation", "Family"], "moods": ["cozy", "euphoric"],
     "keywords": ["superhero", "robot", "friendship", "disney"],
     "poster": _p("/2mxS4wUimwlLmI1xp6QW6NSU361.jpg"),
     "backdrop": None, "overview": "A kid inventor and a huggable healthcare robot form a superhero team.",
     "gem": False, "popularity": 74},
    {"id": 83666, "title": "Moonrise Kingdom", "year": 2012, "runtime": 94, "rating": 7.7, "vote_count": 5500,
     "genres": ["Comedy", "Drama", "Romance"], "moods": ["cozy", "romantic", "nostalgic"],
     "keywords": ["wes anderson", "twee", "kids", "island", "summer"],
     "poster": _p("/y4SXcbNl6CEF2t36icuzuBioj7K.jpg"),
     "backdrop": None, "overview": "Two twelve-year-olds run away together on a New England island in 1965.",
     "gem": True, "popularity": 38},
    {"id": 378064, "title": "A Silent Voice", "year": 2016, "runtime": 130, "rating": 8.3, "vote_count": 3400,
     "genres": ["Animation", "Drama", "Romance"], "moods": ["romantic", "melancholy"],
     "keywords": ["anime", "high school", "deaf", "redemption"],
     "poster": _p("/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg"),
     "backdrop": None, "overview": "A former bully seeks forgiveness from the deaf classmate he tormented.",
     "gem": True, "popularity": 30},
    {"id": 207, "title": "Dead Poets Society", "year": 1989, "runtime": 128, "rating": 8.3, "vote_count": 10500,
     "genres": ["Drama"], "moods": ["nostalgic", "melancholy", "euphoric"],
     "keywords": ["boarding school", "teacher", "poetry", "coming of age"],
     "poster": _p("/tNvKkSnnn4Z6RCBThyK1gfCSSvv.jpg"),
     "backdrop": None, "overview": "An English teacher pulls his boys' school class into poetry — and consequences.",
     "gem": False, "popularity": 58},
    {"id": 11036, "title": "The Notebook", "year": 2004, "runtime": 123, "rating": 7.9, "vote_count": 11000,
     "genres": ["Romance", "Drama"], "moods": ["romantic", "melancholy"],
     "keywords": ["love story", "aging", "letters", "summer romance"],
     "poster": _p("/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg"),
     "backdrop": None, "overview": "A young couple's summer love and the notebook that keeps returning to it.",
     "gem": False, "popularity": 65},
    {"id": 114150, "title": "Pitch Perfect", "year": 2012, "runtime": 112, "rating": 7.1, "vote_count": 6500,
     "genres": ["Comedy", "Music"], "moods": ["euphoric", "cozy"],
     "keywords": ["a cappella", "college", "musical", "friendship"],
     "poster": _p("/gsFoJk9g8W3zgaipRrrURk7LbiF.jpg"),
     "backdrop": None, "overview": "A college a cappella group scraps its way to the national stage.",
     "gem": False, "popularity": 66},
    {"id": 49051, "title": "The Hobbit: An Unexpected Journey", "year": 2012, "runtime": 169, "rating": 7.3, "vote_count": 14500,
     "genres": ["Adventure", "Fantasy"], "moods": ["nostalgic", "euphoric"],
     "keywords": ["fantasy", "dwarves", "hobbit", "middle earth", "adventure"],
     "poster": _p("/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg"),
     "backdrop": None, "overview": "A homebody hobbit reluctantly joins thirteen dwarves to reclaim a stolen kingdom.",
     "gem": False, "popularity": 78},
]


def all_moods():
    return ["nostalgic", "cozy", "chaotic", "melancholy", "euphoric", "weird", "romantic", "angry"]
